defaults:
  - default

strategy: 
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: True

check_val_every_n_epoch: 1

accelerator: gpu
devices: 4
num_nodes: 1
sync_batchnorm: True