# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

defaults:
  - default

strategy: 
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: True

check_val_every_n_epoch: 1

accelerator: gpu
devices: 4
num_nodes: 1
sync_batchnorm: True