_target_: pytorch_lightning.Trainer

devices: 'auto' # also numbers
accelerator: 'auto' #cpu, tpu, (devices=4, accelerator="gpu", strategy="ddp"), (devices="auto", accelerator="auto")

accumulate_grad_batches: 1
min_epochs: 100
max_epochs: 200 #(-1) for infinite
max_steps: -1 #(-1) for infinite
check_val_every_n_epoch: 1
# precision: 16-mixed  # 16, 32, 64, bf16, or None
# precision: 16-mixed # 16, 32
#val_check_interval: ${mult_int:${.accumulate_grad_batches}, 1000}
log_every_n_steps: 1

fast_dev_run: False # True, False, or int (7) (limit_train_batches=1.0, or 10)
# overfit_batches: 0.01
# reload_dataloaders_every_n_epochs: 0

profiler: 'simple' # simple, advanced, pytorch, or None
