# @package _global_

# Activate the debug config through the CLI (e.g. `python ... +debug=fast`)

defaults:
  - hydra: evaluation
  - datamodule: ???
  - model: ???
  - trainer: default
  - logger: wandb
  - callbacks: default
  - override hydra/launcher: submitit_slurm_cpu
  # - optional local: default
  - _self_

# path to work directory
work_dir: ${hydra:runtime.cwd}

# path to data directory
data_dir: ${work_dir}/data

# path to output directory, created dynamically by hydra
output_dir: ${hydra:runtime.output_dir}

ignore_warnings: False
print_config: True

# Seed used to seed everything in the beginning of the run script and to fix randomness in dataset
seed: 42

# determines the log directory's parent folder
logs_subfolder: inference

# determines the log directory's identifier
run_name: ???
